time.sleep(4)
            open("open google")
            time.sleep(2)
            open("open whatsapp")
            time.sleep(2)
            open("open amazon")
            time.sleep(2)
            open("open gmail")
            time.sleep(2)
            os.system("Notepad")